name: edw
profile: cusp
version: '1.0'
config-version: 2

require-dbt-version: ">=0.19.0"

source-paths: ["models"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  database: false
  identifier: false
  schema: false

seeds:
  quote_columns: false

models:
  transient: true